name: Build and Upload Versioned Plugin ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create versioned ZIP with files in root
        run: |
          mkdir -p build
          shopt -s dotglob
          zip -r build/fardar-tracking-bitlab-${VERSION}.zip * -x "build/*" ".git/*" ".github/*"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/fardar-tracking-bitlab-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
