name: Build and Upload Versioned Plugin ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version from tag
        id: version
        run: |
          RAW_TAG="${GITHUB_REF##*/}"
          CLEAN_VERSION="${RAW_TAG#v}"  # remove leading "v"
          echo "VERSION=${CLEAN_VERSION}" >> $GITHUB_ENV

      - name: Update version in PHP plugin header
        run: |
          FILE="fardar-tracking-bitlab.php"
          sed -i -E "s/(\* Version: )([0-9\.]+)/\1${VERSION}/" "$FILE"

      - name: Create plugin folder structure
        run: |
          mkdir -p build/fardar-tracking-bitlab
          shopt -s dotglob
          for item in *; do
            if [[ "$item" != "build" ]]; then
              cp -r "$item" build/fardar-tracking-bitlab/
            fi
          done

          # Remove unwanted dot folders
          rm -rf build/fardar-tracking-bitlab/.git
          rm -rf build/fardar-tracking-bitlab/.github
          rm -rf build/fardar-tracking-bitlab/.vscode
          rm -rf build/fardar-tracking-bitlab/.DS_Store

      - name: Create versioned ZIP
        run: |
          cd build
          zip -r ../fardar-tracking-bitlab-${VERSION}.zip fardar-tracking-bitlab

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: fardar-tracking-bitlab-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
